// Code generated by protoc-gen-go. DO NOT EDIT.
// source: roomMessage.proto

package roomMessage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Player struct {
	PlayerId             int32    `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	PlayName             string   `protobuf:"bytes,2,opt,name=playName,proto3" json:"playName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee2d5dd4590280ee, []int{0}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *Player) GetPlayName() string {
	if m != nil {
		return m.PlayName
	}
	return ""
}

type Room struct {
	RoomId               int32     `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Players              []*Player `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee2d5dd4590280ee, []int{1}
}

func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (m *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(m, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *Room) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

//房间列表获取,只发送给请求客户端
type C2GS_RoomGet struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2GS_RoomGet) Reset()         { *m = C2GS_RoomGet{} }
func (m *C2GS_RoomGet) String() string { return proto.CompactTextString(m) }
func (*C2GS_RoomGet) ProtoMessage()    {}
func (*C2GS_RoomGet) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee2d5dd4590280ee, []int{2}
}

func (m *C2GS_RoomGet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2GS_RoomGet.Unmarshal(m, b)
}
func (m *C2GS_RoomGet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2GS_RoomGet.Marshal(b, m, deterministic)
}
func (m *C2GS_RoomGet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2GS_RoomGet.Merge(m, src)
}
func (m *C2GS_RoomGet) XXX_Size() int {
	return xxx_messageInfo_C2GS_RoomGet.Size(m)
}
func (m *C2GS_RoomGet) XXX_DiscardUnknown() {
	xxx_messageInfo_C2GS_RoomGet.DiscardUnknown(m)
}

var xxx_messageInfo_C2GS_RoomGet proto.InternalMessageInfo

type GS2C_RoomGet struct {
	Rooms                []*Room  `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GS2C_RoomGet) Reset()         { *m = GS2C_RoomGet{} }
func (m *GS2C_RoomGet) String() string { return proto.CompactTextString(m) }
func (*GS2C_RoomGet) ProtoMessage()    {}
func (*GS2C_RoomGet) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee2d5dd4590280ee, []int{3}
}

func (m *GS2C_RoomGet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GS2C_RoomGet.Unmarshal(m, b)
}
func (m *GS2C_RoomGet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GS2C_RoomGet.Marshal(b, m, deterministic)
}
func (m *GS2C_RoomGet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GS2C_RoomGet.Merge(m, src)
}
func (m *GS2C_RoomGet) XXX_Size() int {
	return xxx_messageInfo_GS2C_RoomGet.Size(m)
}
func (m *GS2C_RoomGet) XXX_DiscardUnknown() {
	xxx_messageInfo_GS2C_RoomGet.DiscardUnknown(m)
}

var xxx_messageInfo_GS2C_RoomGet proto.InternalMessageInfo

func (m *GS2C_RoomGet) GetRooms() []*Room {
	if m != nil {
		return m.Rooms
	}
	return nil
}

//房间创建，只发送给请求客户端
type C2GS_RoomCrt struct {
	RoomOwner            *Player  `protobuf:"bytes,1,opt,name=roomOwner,proto3" json:"roomOwner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2GS_RoomCrt) Reset()         { *m = C2GS_RoomCrt{} }
func (m *C2GS_RoomCrt) String() string { return proto.CompactTextString(m) }
func (*C2GS_RoomCrt) ProtoMessage()    {}
func (*C2GS_RoomCrt) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee2d5dd4590280ee, []int{4}
}

func (m *C2GS_RoomCrt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2GS_RoomCrt.Unmarshal(m, b)
}
func (m *C2GS_RoomCrt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2GS_RoomCrt.Marshal(b, m, deterministic)
}
func (m *C2GS_RoomCrt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2GS_RoomCrt.Merge(m, src)
}
func (m *C2GS_RoomCrt) XXX_Size() int {
	return xxx_messageInfo_C2GS_RoomCrt.Size(m)
}
func (m *C2GS_RoomCrt) XXX_DiscardUnknown() {
	xxx_messageInfo_C2GS_RoomCrt.DiscardUnknown(m)
}

var xxx_messageInfo_C2GS_RoomCrt proto.InternalMessageInfo

func (m *C2GS_RoomCrt) GetRoomOwner() *Player {
	if m != nil {
		return m.RoomOwner
	}
	return nil
}

type GS2C_RoomCrt struct {
	ResStatus            int32    `protobuf:"varint,1,opt,name=resStatus,proto3" json:"resStatus,omitempty"`
	RoomId               int32    `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GS2C_RoomCrt) Reset()         { *m = GS2C_RoomCrt{} }
func (m *GS2C_RoomCrt) String() string { return proto.CompactTextString(m) }
func (*GS2C_RoomCrt) ProtoMessage()    {}
func (*GS2C_RoomCrt) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee2d5dd4590280ee, []int{5}
}

func (m *GS2C_RoomCrt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GS2C_RoomCrt.Unmarshal(m, b)
}
func (m *GS2C_RoomCrt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GS2C_RoomCrt.Marshal(b, m, deterministic)
}
func (m *GS2C_RoomCrt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GS2C_RoomCrt.Merge(m, src)
}
func (m *GS2C_RoomCrt) XXX_Size() int {
	return xxx_messageInfo_GS2C_RoomCrt.Size(m)
}
func (m *GS2C_RoomCrt) XXX_DiscardUnknown() {
	xxx_messageInfo_GS2C_RoomCrt.DiscardUnknown(m)
}

var xxx_messageInfo_GS2C_RoomCrt proto.InternalMessageInfo

func (m *GS2C_RoomCrt) GetResStatus() int32 {
	if m != nil {
		return m.ResStatus
	}
	return 0
}

func (m *GS2C_RoomCrt) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

//加入房间
type C2GS_RoomJoin struct {
	RoomId               int32    `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Player               *Player  `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2GS_RoomJoin) Reset()         { *m = C2GS_RoomJoin{} }
func (m *C2GS_RoomJoin) String() string { return proto.CompactTextString(m) }
func (*C2GS_RoomJoin) ProtoMessage()    {}
func (*C2GS_RoomJoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee2d5dd4590280ee, []int{6}
}

func (m *C2GS_RoomJoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2GS_RoomJoin.Unmarshal(m, b)
}
func (m *C2GS_RoomJoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2GS_RoomJoin.Marshal(b, m, deterministic)
}
func (m *C2GS_RoomJoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2GS_RoomJoin.Merge(m, src)
}
func (m *C2GS_RoomJoin) XXX_Size() int {
	return xxx_messageInfo_C2GS_RoomJoin.Size(m)
}
func (m *C2GS_RoomJoin) XXX_DiscardUnknown() {
	xxx_messageInfo_C2GS_RoomJoin.DiscardUnknown(m)
}

var xxx_messageInfo_C2GS_RoomJoin proto.InternalMessageInfo

func (m *C2GS_RoomJoin) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *C2GS_RoomJoin) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

type GS2C_RoomJoin struct {
	ResStatus            int32    `protobuf:"varint,1,opt,name=resStatus,proto3" json:"resStatus,omitempty"`
	RoomInfo             *Room    `protobuf:"bytes,2,opt,name=roomInfo,proto3" json:"roomInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GS2C_RoomJoin) Reset()         { *m = GS2C_RoomJoin{} }
func (m *GS2C_RoomJoin) String() string { return proto.CompactTextString(m) }
func (*GS2C_RoomJoin) ProtoMessage()    {}
func (*GS2C_RoomJoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee2d5dd4590280ee, []int{7}
}

func (m *GS2C_RoomJoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GS2C_RoomJoin.Unmarshal(m, b)
}
func (m *GS2C_RoomJoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GS2C_RoomJoin.Marshal(b, m, deterministic)
}
func (m *GS2C_RoomJoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GS2C_RoomJoin.Merge(m, src)
}
func (m *GS2C_RoomJoin) XXX_Size() int {
	return xxx_messageInfo_GS2C_RoomJoin.Size(m)
}
func (m *GS2C_RoomJoin) XXX_DiscardUnknown() {
	xxx_messageInfo_GS2C_RoomJoin.DiscardUnknown(m)
}

var xxx_messageInfo_GS2C_RoomJoin proto.InternalMessageInfo

func (m *GS2C_RoomJoin) GetResStatus() int32 {
	if m != nil {
		return m.ResStatus
	}
	return 0
}

func (m *GS2C_RoomJoin) GetRoomInfo() *Room {
	if m != nil {
		return m.RoomInfo
	}
	return nil
}

//退出房间
type C2GS_RoomQuit struct {
	PlayerId             int32    `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	RoomId               int32    `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2GS_RoomQuit) Reset()         { *m = C2GS_RoomQuit{} }
func (m *C2GS_RoomQuit) String() string { return proto.CompactTextString(m) }
func (*C2GS_RoomQuit) ProtoMessage()    {}
func (*C2GS_RoomQuit) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee2d5dd4590280ee, []int{8}
}

func (m *C2GS_RoomQuit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2GS_RoomQuit.Unmarshal(m, b)
}
func (m *C2GS_RoomQuit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2GS_RoomQuit.Marshal(b, m, deterministic)
}
func (m *C2GS_RoomQuit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2GS_RoomQuit.Merge(m, src)
}
func (m *C2GS_RoomQuit) XXX_Size() int {
	return xxx_messageInfo_C2GS_RoomQuit.Size(m)
}
func (m *C2GS_RoomQuit) XXX_DiscardUnknown() {
	xxx_messageInfo_C2GS_RoomQuit.DiscardUnknown(m)
}

var xxx_messageInfo_C2GS_RoomQuit proto.InternalMessageInfo

func (m *C2GS_RoomQuit) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *C2GS_RoomQuit) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

type GS2C_RoomQuit struct {
	ResStatus            int32    `protobuf:"varint,1,opt,name=resStatus,proto3" json:"resStatus,omitempty"`
	PlayerId             int32    `protobuf:"varint,2,opt,name=playerId,proto3" json:"playerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GS2C_RoomQuit) Reset()         { *m = GS2C_RoomQuit{} }
func (m *GS2C_RoomQuit) String() string { return proto.CompactTextString(m) }
func (*GS2C_RoomQuit) ProtoMessage()    {}
func (*GS2C_RoomQuit) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee2d5dd4590280ee, []int{9}
}

func (m *GS2C_RoomQuit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GS2C_RoomQuit.Unmarshal(m, b)
}
func (m *GS2C_RoomQuit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GS2C_RoomQuit.Marshal(b, m, deterministic)
}
func (m *GS2C_RoomQuit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GS2C_RoomQuit.Merge(m, src)
}
func (m *GS2C_RoomQuit) XXX_Size() int {
	return xxx_messageInfo_GS2C_RoomQuit.Size(m)
}
func (m *GS2C_RoomQuit) XXX_DiscardUnknown() {
	xxx_messageInfo_GS2C_RoomQuit.DiscardUnknown(m)
}

var xxx_messageInfo_GS2C_RoomQuit proto.InternalMessageInfo

func (m *GS2C_RoomQuit) GetResStatus() int32 {
	if m != nil {
		return m.ResStatus
	}
	return 0
}

func (m *GS2C_RoomQuit) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

//玩家准备
type C2GS_PlayerReady struct {
	PlayerId             int32    `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	RoomId               int32    `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2GS_PlayerReady) Reset()         { *m = C2GS_PlayerReady{} }
func (m *C2GS_PlayerReady) String() string { return proto.CompactTextString(m) }
func (*C2GS_PlayerReady) ProtoMessage()    {}
func (*C2GS_PlayerReady) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee2d5dd4590280ee, []int{10}
}

func (m *C2GS_PlayerReady) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2GS_PlayerReady.Unmarshal(m, b)
}
func (m *C2GS_PlayerReady) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2GS_PlayerReady.Marshal(b, m, deterministic)
}
func (m *C2GS_PlayerReady) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2GS_PlayerReady.Merge(m, src)
}
func (m *C2GS_PlayerReady) XXX_Size() int {
	return xxx_messageInfo_C2GS_PlayerReady.Size(m)
}
func (m *C2GS_PlayerReady) XXX_DiscardUnknown() {
	xxx_messageInfo_C2GS_PlayerReady.DiscardUnknown(m)
}

var xxx_messageInfo_C2GS_PlayerReady proto.InternalMessageInfo

func (m *C2GS_PlayerReady) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *C2GS_PlayerReady) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

type GS2C_PlayerReady struct {
	ResStatus            int32    `protobuf:"varint,1,opt,name=resStatus,proto3" json:"resStatus,omitempty"`
	PlayerId             int32    `protobuf:"varint,2,opt,name=playerId,proto3" json:"playerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GS2C_PlayerReady) Reset()         { *m = GS2C_PlayerReady{} }
func (m *GS2C_PlayerReady) String() string { return proto.CompactTextString(m) }
func (*GS2C_PlayerReady) ProtoMessage()    {}
func (*GS2C_PlayerReady) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee2d5dd4590280ee, []int{11}
}

func (m *GS2C_PlayerReady) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GS2C_PlayerReady.Unmarshal(m, b)
}
func (m *GS2C_PlayerReady) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GS2C_PlayerReady.Marshal(b, m, deterministic)
}
func (m *GS2C_PlayerReady) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GS2C_PlayerReady.Merge(m, src)
}
func (m *GS2C_PlayerReady) XXX_Size() int {
	return xxx_messageInfo_GS2C_PlayerReady.Size(m)
}
func (m *GS2C_PlayerReady) XXX_DiscardUnknown() {
	xxx_messageInfo_GS2C_PlayerReady.DiscardUnknown(m)
}

var xxx_messageInfo_GS2C_PlayerReady proto.InternalMessageInfo

func (m *GS2C_PlayerReady) GetResStatus() int32 {
	if m != nil {
		return m.ResStatus
	}
	return 0
}

func (m *GS2C_PlayerReady) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func init() {
	proto.RegisterType((*Player)(nil), "Player")
	proto.RegisterType((*Room)(nil), "Room")
	proto.RegisterType((*C2GS_RoomGet)(nil), "C2GS_RoomGet")
	proto.RegisterType((*GS2C_RoomGet)(nil), "GS2C_RoomGet")
	proto.RegisterType((*C2GS_RoomCrt)(nil), "C2GS_RoomCrt")
	proto.RegisterType((*GS2C_RoomCrt)(nil), "GS2C_RoomCrt")
	proto.RegisterType((*C2GS_RoomJoin)(nil), "C2GS_RoomJoin")
	proto.RegisterType((*GS2C_RoomJoin)(nil), "GS2C_RoomJoin")
	proto.RegisterType((*C2GS_RoomQuit)(nil), "C2GS_RoomQuit")
	proto.RegisterType((*GS2C_RoomQuit)(nil), "GS2C_RoomQuit")
	proto.RegisterType((*C2GS_PlayerReady)(nil), "C2GS_PlayerReady")
	proto.RegisterType((*GS2C_PlayerReady)(nil), "GS2C_PlayerReady")
}

func init() { proto.RegisterFile("roomMessage.proto", fileDescriptor_ee2d5dd4590280ee) }

var fileDescriptor_ee2d5dd4590280ee = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x5f, 0x4b, 0xf3, 0x30,
	0x14, 0x87, 0x69, 0xdf, 0xb7, 0xdd, 0x7a, 0xdc, 0x64, 0xf6, 0x42, 0x8a, 0x0a, 0x76, 0x01, 0xa1,
	0x20, 0xf4, 0xa2, 0xe2, 0xbd, 0x52, 0xb1, 0x4e, 0xfc, 0x33, 0xdb, 0x0f, 0x20, 0x91, 0x45, 0x19,
	0xd8, 0x66, 0x24, 0x19, 0xb2, 0x6f, 0x2f, 0x49, 0xd3, 0x2c, 0x5e, 0xac, 0x17, 0xbb, 0xdb, 0x39,
	0x87, 0xf3, 0x9c, 0xe7, 0x97, 0x51, 0x38, 0x62, 0x94, 0xd6, 0xcf, 0x84, 0x73, 0xfc, 0x45, 0xd2,
	0x15, 0xa3, 0x82, 0xa2, 0x1b, 0xf0, 0xe7, 0xdf, 0x78, 0x43, 0x58, 0x78, 0x02, 0xc3, 0x95, 0xfa,
	0x35, 0x5b, 0x44, 0x4e, 0xec, 0x24, 0x5e, 0x69, 0xea, 0x6e, 0xf6, 0x82, 0x6b, 0x12, 0xb9, 0xb1,
	0x93, 0x04, 0xa5, 0xa9, 0xd1, 0x2d, 0xfc, 0x2f, 0x29, 0xad, 0xc3, 0x63, 0xf0, 0x25, 0xde, 0x6c,
	0xeb, 0x2a, 0x9c, 0xc2, 0xa0, 0xe5, 0xf0, 0xc8, 0x8d, 0xff, 0x25, 0x07, 0xd9, 0x20, 0x6d, 0x2f,
	0x96, 0x5d, 0x1f, 0x1d, 0xc2, 0x28, 0xcf, 0x8a, 0xea, 0x5d, 0x72, 0x0a, 0x22, 0xd0, 0x25, 0x8c,
	0x8a, 0x2a, 0xcb, 0xbb, 0x3a, 0x3c, 0x05, 0x4f, 0xc2, 0x78, 0xe4, 0x28, 0x80, 0x97, 0xca, 0x41,
	0xd9, 0xf6, 0xd0, 0xb5, 0xb5, 0x9c, 0x33, 0x11, 0x5e, 0x40, 0x20, 0x07, 0xaf, 0x3f, 0x0d, 0x61,
	0x4a, 0xc5, 0xba, 0xb8, 0x9d, 0xa0, 0x3b, 0xeb, 0x86, 0x5c, 0x3b, 0x83, 0x80, 0x11, 0x5e, 0x09,
	0x2c, 0xd6, 0x5c, 0x27, 0xd8, 0x36, 0xac, 0x70, 0xae, 0x1d, 0x0e, 0x3d, 0xc0, 0xd8, 0x1c, 0x7f,
	0xa4, 0xcb, 0x66, 0xe7, 0x2b, 0x9c, 0x83, 0xdf, 0xa6, 0x55, 0x00, 0x4b, 0x49, 0xb7, 0xd1, 0x1c,
	0xc6, 0xc6, 0x47, 0x91, 0xfa, 0x85, 0xa6, 0x30, 0x54, 0xe4, 0xe6, 0x93, 0x6a, 0xa2, 0x7e, 0x15,
	0xd3, 0x46, 0xb9, 0xe5, 0xf6, 0xb6, 0x5e, 0x8a, 0xde, 0x7f, 0x78, 0x57, 0xc0, 0x99, 0xa5, 0xa5,
	0x20, 0xfd, 0x5a, 0xf6, 0x09, 0xf7, 0xef, 0x09, 0x74, 0x0f, 0x13, 0xe5, 0xa3, 0x83, 0x13, 0xbc,
	0xd8, 0xec, 0xa5, 0xf4, 0x04, 0x13, 0xa5, 0x64, 0x73, 0xf6, 0xb6, 0xfa, 0xf0, 0xd5, 0x77, 0x70,
	0xf5, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x68, 0x85, 0xca, 0x90, 0x1c, 0x03, 0x00, 0x00,
}
