// Code generated by protoc-gen-go. DO NOT EDIT.
// source: appclose.proto

package appclose

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type C2GS_AppClose struct {
	PlayerId             int32    `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2GS_AppClose) Reset()         { *m = C2GS_AppClose{} }
func (m *C2GS_AppClose) String() string { return proto.CompactTextString(m) }
func (*C2GS_AppClose) ProtoMessage()    {}
func (*C2GS_AppClose) Descriptor() ([]byte, []int) {
	return fileDescriptor_97f3c63346366e68, []int{0}
}

func (m *C2GS_AppClose) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2GS_AppClose.Unmarshal(m, b)
}
func (m *C2GS_AppClose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2GS_AppClose.Marshal(b, m, deterministic)
}
func (m *C2GS_AppClose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2GS_AppClose.Merge(m, src)
}
func (m *C2GS_AppClose) XXX_Size() int {
	return xxx_messageInfo_C2GS_AppClose.Size(m)
}
func (m *C2GS_AppClose) XXX_DiscardUnknown() {
	xxx_messageInfo_C2GS_AppClose.DiscardUnknown(m)
}

var xxx_messageInfo_C2GS_AppClose proto.InternalMessageInfo

func (m *C2GS_AppClose) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func init() {
	proto.RegisterType((*C2GS_AppClose)(nil), "C2GS_AppClose")
}

func init() { proto.RegisterFile("appclose.proto", fileDescriptor_97f3c63346366e68) }

var fileDescriptor_97f3c63346366e68 = []byte{
	// 81 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x2c, 0x28, 0x48,
	0xce, 0xc9, 0x2f, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xd2, 0xe6, 0xe2, 0x75, 0x36,
	0x72, 0x0f, 0x8e, 0x77, 0x2c, 0x28, 0x70, 0x06, 0x09, 0x0b, 0x49, 0x71, 0x71, 0x14, 0xe4, 0x24,
	0x56, 0xa6, 0x16, 0x79, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0xc1, 0xf9, 0x49, 0x6c,
	0x60, 0x3d, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x27, 0x4a, 0xf5, 0xc1, 0x45, 0x00, 0x00,
	0x00,
}
