// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gameEnter.proto

package gameEnter

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//进入游戏时向服务器发送客户端信息
type C2GS_GameEnter struct {
	PlayerId             int32    `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	PlayerName           string   `protobuf:"bytes,2,opt,name=playerName,proto3" json:"playerName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2GS_GameEnter) Reset()         { *m = C2GS_GameEnter{} }
func (m *C2GS_GameEnter) String() string { return proto.CompactTextString(m) }
func (*C2GS_GameEnter) ProtoMessage()    {}
func (*C2GS_GameEnter) Descriptor() ([]byte, []int) {
	return fileDescriptor_06a5afbe6e4315ad, []int{0}
}

func (m *C2GS_GameEnter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2GS_GameEnter.Unmarshal(m, b)
}
func (m *C2GS_GameEnter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2GS_GameEnter.Marshal(b, m, deterministic)
}
func (m *C2GS_GameEnter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2GS_GameEnter.Merge(m, src)
}
func (m *C2GS_GameEnter) XXX_Size() int {
	return xxx_messageInfo_C2GS_GameEnter.Size(m)
}
func (m *C2GS_GameEnter) XXX_DiscardUnknown() {
	xxx_messageInfo_C2GS_GameEnter.DiscardUnknown(m)
}

var xxx_messageInfo_C2GS_GameEnter proto.InternalMessageInfo

func (m *C2GS_GameEnter) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *C2GS_GameEnter) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

type GS2C_GameEnter struct {
	ResStatus            int32    `protobuf:"varint,1,opt,name=resStatus,proto3" json:"resStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GS2C_GameEnter) Reset()         { *m = GS2C_GameEnter{} }
func (m *GS2C_GameEnter) String() string { return proto.CompactTextString(m) }
func (*GS2C_GameEnter) ProtoMessage()    {}
func (*GS2C_GameEnter) Descriptor() ([]byte, []int) {
	return fileDescriptor_06a5afbe6e4315ad, []int{1}
}

func (m *GS2C_GameEnter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GS2C_GameEnter.Unmarshal(m, b)
}
func (m *GS2C_GameEnter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GS2C_GameEnter.Marshal(b, m, deterministic)
}
func (m *GS2C_GameEnter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GS2C_GameEnter.Merge(m, src)
}
func (m *GS2C_GameEnter) XXX_Size() int {
	return xxx_messageInfo_GS2C_GameEnter.Size(m)
}
func (m *GS2C_GameEnter) XXX_DiscardUnknown() {
	xxx_messageInfo_GS2C_GameEnter.DiscardUnknown(m)
}

var xxx_messageInfo_GS2C_GameEnter proto.InternalMessageInfo

func (m *GS2C_GameEnter) GetResStatus() int32 {
	if m != nil {
		return m.ResStatus
	}
	return 0
}

func init() {
	proto.RegisterType((*C2GS_GameEnter)(nil), "C2GS_GameEnter")
	proto.RegisterType((*GS2C_GameEnter)(nil), "GS2C_GameEnter")
}

func init() { proto.RegisterFile("gameEnter.proto", fileDescriptor_06a5afbe6e4315ad) }

var fileDescriptor_06a5afbe6e4315ad = []byte{
	// 124 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0x4f, 0xcc, 0x4d,
	0x75, 0xcd, 0x2b, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xf2, 0xe1, 0xe2, 0x73,
	0x36, 0x72, 0x0f, 0x8e, 0x77, 0x87, 0x89, 0x0b, 0x49, 0x71, 0x71, 0x14, 0xe4, 0x24, 0x56, 0xa6,
	0x16, 0x79, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0xc1, 0xf9, 0x42, 0x72, 0x5c, 0x5c,
	0x10, 0xb6, 0x5f, 0x62, 0x6e, 0xaa, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x92, 0x88, 0x92,
	0x1e, 0x17, 0x9f, 0x7b, 0xb0, 0x91, 0x33, 0x92, 0x69, 0x32, 0x5c, 0x9c, 0x45, 0xa9, 0xc5, 0xc1,
	0x25, 0x89, 0x25, 0xa5, 0xc5, 0x50, 0xe3, 0x10, 0x02, 0x49, 0x6c, 0x60, 0x47, 0x18, 0x03, 0x02,
	0x00, 0x00, 0xff, 0xff, 0xfe, 0xb3, 0x70, 0xfb, 0x97, 0x00, 0x00, 0x00,
}
